# Purpose: Docker Compose configuration for local development and testing

version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: lecommit-webapp:latest
    container_name: lecommit-webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 